#!/usr/bin/env python3

print("importing main from Python package simontest in simon_node1")
from simontest import main
print("imported main from Python package simontest in simon_node1")

if __name__ == '__main__':
	print("executing main() in simon_node1")
	main()

