#!/usr/bin/env python3

print("importing bar_fn from Python package simontest in simon_script1")
from simontest.simon_pythonsubpackage1 import bar_fn
print("imported bar_fn from Python package simontest in simon_script1")

if __name__ == '__main__':
	print("executing bar_fn() in simon_script1")
	bar_fn()

